language: python
python:
  - "2.7"

env:
  - DOCKER_COMPOSE_VERSION=1.17.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo docker-compose -f docker-compose.dev.yml up -d etcd memcached redis
  - pip install pytz coveralls

services:
  - docker

# command to run tests
script:
  docker-compose -f docker-compose.dev.yml run sherlock

after_success:
  coveralls
