language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install pytz
  - pip install coveralls

services:
  - redis-server

# command to run tests
script:
  coverage run --source=sherlock setup.py test

after_success:
  coveralls
